In [7]:
# Imprimindo a tabela de estoque

import pyodbc
import pandas as pd

dados_conexao = ("Driver={SQLite3 ODBC Driver};Server=localhost;Database=Estoque.db")
conexao = pyodbc.connect(dados_conexao)
cursor = conexao.cursor()

def relatorio():
    cursor.execute("SELECT * FROM Estoque")
    # esse comando vai pegar as informações do cursor e armazenar ela na variável estoque, no formato de uma lista de tuplas
    estoque = cursor.fetchall()
    descrição = cursor.description
    # variável para igualar o nome das colunas do DB Browser com a tabela abaixo.
    colunas = [tupla[0] for tupla in descrição]
    #print(colunas) 
    tabela_estoque = pd.DataFrame.from_records(estoque, columns=colunas)
    display(tabela_estoque)
    


relatorio()

print(tabela_estoque)

cursor.close()
conexao.close()

   Id     Produto  Quantidade DataValidade  Lote
0   1        Copo      1270.0   2050-12-30     1
1   2     Corante       500.0   2024-11-15     1
2   8        Faca      2990.0   2030-09-15     6
3   9        Copo      3000.0   2040-08-10     2
4  10  Guardanapo      8000.0   2050-11-25     6
5  11        Copo      2500.0   2030-10-15     3
6  12   Copo 50ml      2000.0   2030-12-10     1

NameError: name 'tabela_estoque' is not defined

In [4]:
#cursor.close()
#conexao.close()